import { StyleSheet } from "react-native";

export default StyleSheet.create({
  footerContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    width: "100%",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  footer: {
    width: "100%",
    height: 70,
    backgroundColor: "#fff",
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
    paddingHorizontal: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    position: "relative",
  },
  footerLeft: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingRight: 40, // Espaço para o botão no centro
  },
  footerRight: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingLeft: 40, // Espaço para o botão no centro
  },
  fabContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#33CA7F",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    bottom: 35, // Posiciona o botão para que a parte inferior entre na concavidade
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 10,
  },
  footerWithIndent: {
    width: "100%",
    height: 70,
    position: "relative",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    overflow: "visible",
  },
  footerSvg: {
    position: "absolute",
    top: 0,
    left: 0,
  },
  footerContent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    zIndex: 1,
  },
  footerLeftContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingRight: 40,
  },
  footerCenterSpacer: {
    width: 80,
  },
  footerRightContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingLeft: 40,
  },
  footerRightIcon: {
    marginLeft: 20,
    width: 80,
    height: 80,
  },
  footerRightIconFirst: {
    marginLeft: 0,
    width: 80,
    height: 80,
  },
  footerIcon: {
    width: 30,
    height: 30,
  }
})