import { StyleSheet } from "react-native";

export default StyleSheet.create({
  quizCard: {
    backgroundColor: "transparent",
    borderRadius: 14,
    padding: 0,
    marginBottom: 16,
    flexDirection: "row",
    gap: 0,
    borderWidth: 1,
    borderColor: "#fff",
    overflow: "hidden",
    maxHeight: 150,
  },
  imageContainer: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 13,
    borderBottomLeftRadius: 13,
    padding: 8,
    justifyContent: "center",
    alignItems: "center",
    width: 100,
    alignSelf: "stretch",
  },
  quizImage: {
    width: "100%",
    height: "100%",
  },
  contentContainer: {
    flex: 1,
    backgroundColor: "transparent",
    padding: 8,
    paddingLeft: 10,
    paddingRight: 8,
    minWidth: 0,
    justifyContent: "space-between",
  },
  contentTop: {
    flex: 1,
  },
  quizTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 2,
  },
  quizDescription: {
    color: "#fff",
    marginTop: 2,
    fontSize: 12,
  },
  tagContainer: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "#fff",
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 20,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: -8,
  },
  tagImage: {
    width: 14,
    height: 14,
  },
  quizTag: {
    color: "#fff",
    fontSize: 11,
  },
  quizCardExpanded: {
    backgroundColor: "transparent",
    borderRadius: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#fff",
    overflow: "hidden",
  },
  expandedTopSection: {
    backgroundColor: "#fff",
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 120,
  },
  expandedImage: {
    width: 100,
    height: 100,
  },
  expandedBottomSection: {
    backgroundColor: "#0AAD60",
    padding: 20,
  },
  expandedTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 12,
  },
  expandedDescription: {
    color: "#fff",
    fontSize: 14,
    marginBottom: 20,
    lineHeight: 20,
  },
  buttonStart: {
    backgroundColor: "#0A9152",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  buttonStartText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
  },
})