import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    backgroundColor: "#33CA7F",
    paddingHorizontal: 20,
    flexGrow: 1,
  },
  header: {
    paddingTop: 50,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
    marginRight: 24,
  },
  label: {
    color: "#fff",
    marginBottom: 6,
  },
  input: {
    backgroundColor: "#3DDC91",
    borderRadius: 10,
    padding: 14,
    color: "#fff",
    marginBottom: 16,
  },
  optionsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  optionBox: {
    width: "48%",
    backgroundColor: "#2FAF73",
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
  },
  optionTitle: {
    color: "#E8FFF3",
    fontSize: 12,
    marginBottom: 6,
  },
  optionInput: {
    backgroundColor: "#3DDC91",
    borderRadius: 8,
    padding: 10,
    color: "#fff",
    marginBottom: 8,
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    gap: 8,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: "#fff",
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxChecked: {
    backgroundColor: "#22C55E",
    borderColor: "#22C55E",
  },
  checkboxLabel: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "500",
  },
  selectedTagsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 16,
    marginTop: 8,
  },
  selectedTag: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#2FAF73",
    borderWidth: 1,
    borderColor: "#fff",
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 8,
    marginRight: 8,
    marginBottom: 8,
  },
  removeTagButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#1E8E5A",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 6,
  },
  selectedTagText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "500",
  },
  tagsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 8,
  },
  tag: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#2FAF73",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 20,
    marginRight: 8,
    marginBottom: 8,
  },
  tagImage: {
    width: 20,
    height: 20,
    borderRadius: 10,
    marginRight: 6,
  },
  tagText: {
    color: "#fff",
    fontSize: 12,
  },
  loadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 20,
  },
  loadingText: {
    color: "#fff",
    fontSize: 12,
    marginLeft: 8,
  },
  submitButton: {
    backgroundColor: "#1E8E5A",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 20,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitText: {
    color: "#fff",
    fontWeight: "bold",
  },
  optionLabel: {
    color: "#fff",
    fontSize: 12,
    marginBottom: 6,
  },
  correctOption: {
    borderWidth: 2,
    borderColor: "#22C55E",
  },
  duplicateOption: {
    borderWidth: 2,
    borderColor: "#FF5252",
  },
});